$ErrorActionPreference="Stop"
$CodexDir=Join-Path $HOME ".codex"
$EnvFile=Join-Path $CodexDir ".env"
$CandidatePorts=@(7890,7897,7891,10809,10808,1080)

function Test-LocalPort([int]$Port){
  try{
    $c=New-Object Net.Sockets.TcpClient
    $a=$c.BeginConnect("127.0.0.1",$Port,$null,$null)
    $ok=$a.AsyncWaitHandle.WaitOne(400)
    if($ok -and $c.Connected){$c.EndConnect($a);$c.Close();return $true}
    $c.Close()
  }catch{}
  return $false
}

Write-Host "Codex Doctor V1 - Proxy Auto Fix" -ForegroundColor Cyan
$Detected=@($CandidatePorts|Where-Object{Test-LocalPort $_})
if(-not $Detected.Count){
  Write-Host "No common local proxy port detected." -ForegroundColor Red
  Read-Host "Press Enter"
  exit 1
}

$Port=$Detected[0]
$Proxy="http://127.0.0.1:$Port"
New-Item -ItemType Directory -Force -Path $CodexDir|Out-Null

if(Test-Path $EnvFile){
  Copy-Item $EnvFile "$EnvFile.backup_$(Get-Date -Format yyyyMMdd_HHmmss)" -Force
  $old=Get-Content $EnvFile|Where-Object{
    $_ -notmatch '^\s*(HTTP_PROXY|HTTPS_PROXY|http_proxy|https_proxy|NO_PROXY|no_proxy)\s*='
  }
}else{$old=@()}

$lines=@($old)+@(
  "",
  "# Codex proxy - generated by Codex Doctor V1",
  "HTTP_PROXY=$Proxy",
  "HTTPS_PROXY=$Proxy",
  "http_proxy=$Proxy",
  "https_proxy=$Proxy",
  "NO_PROXY=localhost,127.0.0.1,::1",
  "no_proxy=localhost,127.0.0.1,::1"
)
Set-Content $EnvFile $lines -Encoding UTF8

foreach($n in @("HTTP_PROXY","HTTPS_PROXY","http_proxy","https_proxy")){
 [Environment]::SetEnvironmentVariable($n,$Proxy,"User")
}
foreach($n in @("NO_PROXY","no_proxy")){
 [Environment]::SetEnvironmentVariable($n,"localhost,127.0.0.1,::1","User")
}

Write-Host "Configured Codex proxy: $Proxy" -ForegroundColor Green
Write-Host "Fully exit and restart Codex Desktop." -ForegroundColor Yellow
Read-Host "Press Enter"
